# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Lumogis
"""Harness for ``scripts/render-lumogis-site-pages.mjs`` (LUM-226)."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
SCRIPT = REPO / "scripts" / "render-lumogis-site-pages.mjs"
FIXTURES = Path(__file__).resolve().parent / "fixtures" / "site-pages"
SHELL = FIXTURES / "page-shell-fixture.html"


def _node_available() -> bool:
    return subprocess.run(["node", "--version"], capture_output=True).returncode == 0


def _run_render(
    tmp_path: Path,
    *,
    capabilities_md: Path | None = None,
    changelog_md: Path | None = None,
    extra_args: list[str] | None = None,
) -> subprocess.CompletedProcess[str]:
    args = [
        "node",
        str(SCRIPT),
        "--site-out",
        str(tmp_path),
        "--shell",
        str(SHELL),
    ]
    if capabilities_md is not None:
        args.extend(["--capabilities-md", str(capabilities_md)])
    if changelog_md is not None:
        args.extend(["--changelog-md", str(changelog_md)])
    if extra_args:
        args.extend(extra_args)
    return subprocess.run(
        args,
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.mark.skipif(not _node_available(), reason="node not available")
def test_render_site_pages_writes_capabilities_and_changelog(tmp_path: Path) -> None:
    result = _run_render(
        tmp_path,
        capabilities_md=FIXTURES / "capabilities-minimal.md",
        changelog_md=FIXTURES / "changelog-with-unreleased.md",
        extra_args=["--omit-unreleased", "--strip-ticket-ids"],
    )
    assert result.returncode == 0, result.stderr
    cap_html = tmp_path / "capabilities" / "index.html"
    log_html = tmp_path / "changelog" / "index.html"
    assert cap_html.is_file()
    assert log_html.is_file()
    cap_text = cap_html.read_text(encoding="utf-8")
    assert "generated by scripts/render-lumogis-site-pages.mjs" in cap_text
    assert "lumogis-devtools" not in cap_text.lower()


@pytest.mark.skipif(not _node_available(), reason="node not available")
def test_omit_unreleased_excludes_section(tmp_path: Path) -> None:
    result = _run_render(
        tmp_path,
        capabilities_md=FIXTURES / "capabilities-minimal.md",
        changelog_md=FIXTURES / "changelog-with-unreleased.md",
        extra_args=["--omit-unreleased", "--strip-ticket-ids"],
    )
    assert result.returncode == 0, result.stderr
    log_text = (tmp_path / "changelog" / "index.html").read_text(encoding="utf-8")
    assert "[Unreleased]" not in log_text
    assert "0.7.1" in log_text


@pytest.mark.skipif(not _node_available(), reason="node not available")
def test_strip_ticket_ids_removes_lum_refs(tmp_path: Path) -> None:
    result = _run_render(
        tmp_path,
        capabilities_md=FIXTURES / "capabilities-minimal.md",
        changelog_md=FIXTURES / "changelog-with-unreleased.md",
        extra_args=["--omit-unreleased", "--strip-ticket-ids"],
    )
    assert result.returncode == 0, result.stderr
    log_text = (tmp_path / "changelog" / "index.html").read_text(encoding="utf-8")
    assert "LUM-465" not in log_text


@pytest.mark.skipif(not _node_available(), reason="node not available")
def test_forbidden_substrings_fail_render(tmp_path: Path) -> None:
    result = _run_render(
        tmp_path,
        capabilities_md=FIXTURES / "capabilities-minimal.md",
        changelog_md=FIXTURES / "changelog-forbidden.md",
        extra_args=["--omit-unreleased", "--strip-ticket-ids"],
    )
    assert result.returncode != 0


@pytest.mark.skipif(not _node_available(), reason="node not available")
def test_private_doc_link_fails(tmp_path: Path) -> None:
    result = _run_render(
        tmp_path,
        capabilities_md=FIXTURES / "capabilities-private-link.md",
        changelog_md=FIXTURES / "changelog-with-unreleased.md",
        extra_args=["--omit-unreleased", "--strip-ticket-ids"],
    )
    assert result.returncode != 0


@pytest.mark.skipif(not _node_available(), reason="node not available")
def test_missing_site_out_fails() -> None:
    env = {
        k: v
        for k, v in __import__("os").environ.items()
        if k not in ("LUMOGIS_SITE_ROOT", "LUMOGIS_RENDER_DISABLE_SIBLING")
    }
    env["LUMOGIS_RENDER_DISABLE_SIBLING"] = "1"
    result = subprocess.run(
        [
            "node",
            str(SCRIPT),
            "--capabilities-md",
            str(FIXTURES / "capabilities-minimal.md"),
            "--changelog-md",
            str(FIXTURES / "changelog-with-unreleased.md"),
            "--shell",
            str(SHELL),
        ],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=False,
        env=env,
    )
    assert result.returncode != 0
