#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Lumogis
"""Generate a docker-compose override that pins service images for rollback (LUM-187).

Reads a tab-separated rollback state file (``service<TAB>image<TAB>ref`` per line)
and writes ``rollback-compose.override.yml`` so ``docker compose up`` uses the
captured digests instead of a floating ``:latest`` tag.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def parse_state_lines(text: str) -> list[tuple[str, str]]:
    """Return ``(service, image_ref)`` pairs from rollback state TSV."""
    pairs: list[tuple[str, str]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) >= 3:
            service, _image, ref = parts[0].strip(), parts[1].strip(), parts[2].strip()
        elif len(parts) == 2:
            # Legacy 2-column state (image<TAB>ref) — cannot map to a service name.
            continue
        else:
            continue
        if service and ref:
            pairs.append((service, ref))
    return pairs


def render_override_yaml(pairs: list[tuple[str, str]]) -> str:
    """Render compose override YAML pinning each service image."""
    if not pairs:
        raise ValueError("no service/image pairs to pin")

    lines = [
        "# Generated by scripts/update/write_rollback_override.py — do not edit.",
        "# Appended to COMPOSE_FILE by scripts/update/rollback.sh.",
        "services:",
    ]
    for service, ref in pairs:
        lines.append(f"  {service}:")
        lines.append(f"    image: {ref}")
        lines.append("    build: !reset null")
    lines.append("")
    return "\n".join(lines)


def write_rollback_override(state_path: Path, out_path: Path) -> int:
    pairs = parse_state_lines(state_path.read_text(encoding="utf-8"))
    if not pairs:
        return 1
    out_path.write_text(render_override_yaml(pairs), encoding="utf-8")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("state_file", type=Path, help="TSV rollback state (service, image, ref)")
    parser.add_argument("out_file", type=Path, help="Output rollback-compose.override.yml path")
    args = parser.parse_args(argv)
    try:
        return write_rollback_override(args.state_file, args.out_file)
    except (OSError, ValueError) as exc:
        print(f"write_rollback_override: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
