#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (C) 2026 Lumogis
"""LUM-618 install-time egress-ACL generator.

Turns a community capability's declared ``external_endpoints`` into a Squid
allow file (``docker/egress-proxy/allow/<id>.txt``) and prints the compose
network-wiring snippet an operator adds to contain it.

Run from the repo root so the orchestrator package resolves::

    python -m scripts.gen_capability_egress_acl --id lumogis.mock.echo \
        --endpoints example.com
    python -m scripts.gen_capability_egress_acl --manifest path/to/manifest.json

Exactly one input source is required (``--manifest`` OR ``--id`` + ``--endpoints``).

Fail-closed: the capability ``id`` is validated FIRST (it becomes a filesystem
path and a Squid ACL name, so an unsafe id is a path-traversal / config-injection
surface — a *community* capability's id is author-controlled), then the endpoints
are validated with the same normaliser Core uses at manifest ingest. Any invalid
input exits non-zero and writes nothing.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _repo_root() -> Path:
    # scripts/ -> repo root
    return Path(__file__).resolve().parent.parent


def _ensure_orchestrator_on_path() -> None:
    """Make ``models.capability`` / ``services.capability_scopes`` importable.

    Internal orchestrator code imports as ``from models.capability import ...``
    because the test/runtime harness puts ``orchestrator/`` on ``sys.path``. This
    standalone script is invoked from the repo root, so replicate that here (in
    addition to the repo root, so ``python -m scripts...`` also works).
    """
    root = _repo_root()
    for p in (str(root), str(root / "orchestrator")):
        if p not in sys.path:
            sys.path.insert(0, p)


_ensure_orchestrator_on_path()

# Reuse the SAME validators Core uses — never re-implement (no drift between
# generation-time and manifest-ingest validation).
from models.capability import normalise_external_endpoints  # noqa: E402
from services.capability_scopes import is_grantable_capability_id  # noqa: E402

ALLOW_DIR = _repo_root() / "docker" / "egress-proxy" / "allow"


class GeneratorError(RuntimeError):
    """Raised on any invalid input (id or endpoints). Fail-closed."""


def _load_from_manifest(path: Path) -> tuple[str, list[str]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise GeneratorError(f"cannot read manifest {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise GeneratorError("manifest is not a JSON object")
    cap_id = data.get("id")
    endpoints = data.get("external_endpoints") or []
    if not isinstance(cap_id, str):
        raise GeneratorError("manifest 'id' missing or not a string")
    if not isinstance(endpoints, list):
        raise GeneratorError("manifest 'external_endpoints' is not a list")
    return cap_id, [str(e) for e in endpoints]


def generate(cap_id: str, raw_endpoints: list[str], *, allow_dir: Path = ALLOW_DIR) -> Path:
    """Validate and write ``<allow_dir>/<cap_id>.txt``. Returns the written path.

    Raises :class:`GeneratorError` (fail-closed) on any invalid input; nothing is
    written in that case.
    """
    # 1) Validate the id BEFORE deriving any path / ACL token from it.
    if not is_grantable_capability_id(cap_id):
        raise GeneratorError(
            f"capability id {cap_id!r} is not a safe identifier "
            "(must match [a-z0-9][a-z0-9._-]{0,42} — no '/', '..', whitespace, "
            "quotes, or newlines); refusing to derive a filename / Squid ACL name "
            "from it"
        )
    # 2) Validate the endpoints with Core's own normaliser (raises on
    #    scheme/port/wildcard/IPv6/IDN/over-cap; de-dupes deterministically).
    try:
        hosts = normalise_external_endpoints(raw_endpoints)
    except (ValueError, TypeError) as exc:
        raise GeneratorError(f"invalid external_endpoints for {cap_id}: {exc}") from exc

    allow_dir.mkdir(parents=True, exist_ok=True)
    out = allow_dir / f"{cap_id}.txt"
    lines = [
        f"# LUM-618 egress allowlist for capability id: {cap_id}",
        "# One bare host / IPv4 per line. Generated by scripts/gen_capability_egress_acl.py",
        "# — do not hand-edit; regenerate when the manifest's external_endpoints change.",
        *hosts,
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def _hosts_from_allow_file(path: Path) -> list[str]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise GeneratorError(f"cannot read allow file {path}: {exc}") from exc
    raw: list[str] = []
    for line in text.splitlines():
        host = line.split("#", 1)[0].strip()
        if host:
            raw.append(host)
    try:
        return list(normalise_external_endpoints(raw))
    except (ValueError, TypeError) as exc:
        raise GeneratorError(f"invalid hosts in allow file {path}: {exc}") from exc


def check(
    cap_id: str, raw_endpoints: list[str], *, allow_dir: Path = ALLOW_DIR
) -> tuple[bool, str]:
    """Compare normalised endpoints to ``allow/<id>.txt``. Returns (ok, message)."""
    if not is_grantable_capability_id(cap_id):
        raise GeneratorError(
            f"capability id {cap_id!r} is not a safe identifier "
            "(must match [a-z0-9][a-z0-9._-]{0,42})"
        )
    try:
        expected = set(normalise_external_endpoints(raw_endpoints))
    except (ValueError, TypeError) as exc:
        raise GeneratorError(f"invalid external_endpoints for {cap_id}: {exc}") from exc

    allow_path = allow_dir / f"{cap_id}.txt"
    if not allow_path.is_file():
        return False, f"missing allow file: {allow_path}"
    actual = set(_hosts_from_allow_file(allow_path))
    if expected == actual:
        return True, f"ok: {allow_path} matches {sorted(expected)}"
    only_manifest = sorted(expected - actual)
    only_allow = sorted(actual - expected)
    return (
        False,
        f"divergence for {cap_id}: only_in_manifest={only_manifest} "
        f"only_in_allow={only_allow}",
    )


def _print_wiring_snippet(cap_id: str) -> None:
    print(
        "\n# ---- compose wiring snippet (add to your egress overlay) ----\n"
        "#   services:\n"
        f"#     {cap_id.replace('.', '-')}:\n"
        "#       networks:\n"
        "#         community-egress-internal:\n"
        "#           ipv4_address: 172.31.0.<N>   # a stable static IP\n"
        "#       environment:\n"
        "#         HTTP_PROXY: http://egress-proxy:3128\n"
        "#         HTTPS_PROXY: http://egress-proxy:3128\n"
        "#         NO_PROXY: localhost,127.0.0.1   # NOT the allowed host\n"
        f"#   Then add '{cap_id}' to the contained_capabilities marker file;\n"
        "#   Core mtime-reloads it on the next OOP dispatch (no restart).",
        file=sys.stderr,
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="LUM-618/LUM-621: generate or check a Squid egress allow file from "
        "a capability's external_endpoints."
    )
    parser.add_argument("--manifest", type=Path, help="Path to a capability manifest JSON.")
    parser.add_argument("--id", dest="cap_id", help="Capability id (with --endpoints).")
    parser.add_argument(
        "--endpoints",
        help="Comma-separated bare hosts/IPv4 (with --id).",
    )
    parser.add_argument(
        "--allow-dir",
        type=Path,
        default=ALLOW_DIR,
        help="Allow-file directory (default: docker/egress-proxy/allow).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare expected endpoints to the existing allow file (no write).",
    )
    args = parser.parse_args(argv)

    manifest_mode = args.manifest is not None
    inline_mode = args.cap_id is not None or args.endpoints is not None
    if manifest_mode == inline_mode:
        parser.error("provide exactly one of --manifest OR (--id and --endpoints)")

    try:
        if manifest_mode:
            cap_id, raw_endpoints = _load_from_manifest(args.manifest)
        else:
            if not args.cap_id or args.endpoints is None:
                parser.error("--id and --endpoints are both required in inline mode")
            cap_id = args.cap_id
            raw_endpoints = [e.strip() for e in args.endpoints.split(",") if e.strip()]
        if args.check:
            ok, msg = check(cap_id, raw_endpoints, allow_dir=args.allow_dir)
            print(msg, file=sys.stderr if not ok else sys.stdout)
            return 0 if ok else 1
        out = generate(cap_id, raw_endpoints, allow_dir=args.allow_dir)
    except GeneratorError as exc:
        print(f"gen_capability_egress_acl: {exc}", file=sys.stderr)
        return 2

    print(str(out))
    _print_wiring_snippet(cap_id)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
