from typing import Protocol


class Embedder(Protocol):
    def ping(self) -> bool: ...

    @property
    def vector_size(self) -> int: ...

    def embed(self, text: str) -> list[float]: ...
    def embed_batch(self, texts: list[str]) -> list[list[float]]: ...
