from typing import Protocol


class GraphStore(Protocol):
    def ping(self) -> bool: ...
    def create_node(self, labels: list[str], properties: dict) -> str: ...
    def create_edge(self, from_id: str, to_id: str, rel_type: str, properties: dict) -> None: ...
    def query(self, cypher: str, params: dict | None = None) -> list[dict]: ...
