from typing import Protocol


class MetadataStore(Protocol):
    def ping(self) -> bool: ...
    def execute(self, query: str, params: tuple | None = None) -> None: ...
    def fetch_one(self, query: str, params: tuple | None = None) -> dict | None: ...
    def fetch_all(self, query: str, params: tuple | None = None) -> list[dict]: ...
