from typing import Protocol


class VectorStore(Protocol):
    def ping(self) -> bool: ...
    def create_collection(self, name: str, vector_size: int) -> None: ...
    def upsert(self, collection: str, id: str, vector: list[float], payload: dict) -> None: ...
    def search(
        self, collection: str, vector: list[float], limit: int, threshold: float
    ) -> list[dict]: ...
    def delete(self, collection: str, id: str) -> None: ...
    def count(self, collection: str) -> int: ...
